#!/bin/sh
LAPTOP=eDP1
DOCK=HDMI1
DOCKPOS=--above
PRESPOS=--right-of

#xplugrc TYPE DEVICE STATUS ["Optional Description"]

if [ "$1" != "display" ]; then
    case "$1,$3,$4" in
        keyboard,connected,*)
            setxkbmap -option caps:escape
            xset r rate 300 50
            ;;
    esac
    exit 0
fi


if [ "$3" = "disconnected" ]; then
    bspc monitor HDMI1 -r
    xrandr --output $2 --off
    bspc wm -r
    bspc wm -o
    exit 0
fi


if [ "$2" = "${DOCK}" ]; then
    xrandr --output $2 --auto ${DOCKPOS} ${LAPTOP} --output ${LAPTOP} --primary
    bspc wm -r
#elif  [ "$1" != "${LAPTOP}" ]; then
#    xrandr --output $2 --auto ${PRESPOS} ${LAPTOP} --primary
else
    xrandr --auto
fi
