#!/usr/bin/env sh

data=$(date '+%Y-%m-%d %H:%M:%S')

echo "= bspwm =============================" >> "$LOGINLOG"
echo "$data" >> "$LOGINLOG"

## wal colors
. "$HOME/.config/bspwm/colors.sh"

sxhkd &
xrdb -load .Xresources &
xset r rate 300 50 &
xset +fp /home/zerinol/.local/share/fonts
xset +fp /home/zerinol/.fonts
xset fp rehash
xset -b &

[ -x $HOME/.local/bin/dual_monitor ] && dual_monitor  2>&1 >> "$LOGINLOG"

# Set pulseaudio profile saida analogica
# pacmd set-card-profile alsa_card.pci-0000_00_1f.3 output:analog-stereo

bspc monitor LVDS -d 1 2 3 4 5
bspc monitor DisplayPort-0 -d 6 7
bspc wm -O LVDS DisplayPort-0
bspc monitor LVDS-1-2 -r 2>&1 >> "$LOGINLOG"

bspc config border_width        2
bspc config window_gap          4

bspc config normal_border_color $color1
bspc config focused_border_color $color4
bspc config active_border_color $color9
bspc config presel_feedback_color $color6

bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a XCalc state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Gedit state=floating
bspc rule -a mpv state=floating rectangle=640x360+50+70
bspc rule -a ncmpcpp:* state=floating rectangle=1300x412+25+183
bspc rule -a *:pad state=floating rectangle=716x356+400+30
bspc rule -a *:cal state=floating rectangle=716x206+400+30
bspc rule -a *:tremc state=floating rectangle=800x600+400+50
bspc rule -a *:metronome state=floating
bspc rule -a Emacs state=floating rectangle=775x680+350+30
bspc rule -a zoom state=floating
bspc rule -a Ramme state=floating
bspc rule -a Zathura state=tiled
bspc rule -a *:Kunst state=floating
bspc rule -a *:float_sc state=floating
bspc rule -a PdWindow:* state=floating
bspc rule -a HelpBrowser:* state=floating
bspc rule -a Processing:* state=floating
bspc rule -a Ripcord:* state=floating
bspc rule -a Overgrive:* state=floating
bspc rule -a Peek:* state=floating

# [ -z $(ps aux | grep mark.sh | grep -v grep) ] && $HOME/.config/bspwm/mark.sh &

$HOME/.config/polybar/forest/launch.sh 2>&1 >> "$LOGINLOG" &
feh --recursive --randomize --bg-fill ~/db/wpp
