#!/usr/bin/env sh

data=$(date '+%Y-%m-%d %H:%M:%S')

echo "= bspwm =============================" >> "$LOGINLOG"
echo "$data" >> "$LOGINLOG"

## wal colors
. "$HOME/.cache/wal/colors.sh"

sxhkd &
xrdb -load .Xdefaults &
xset r rate 300 50 &
xset +fp /home/zerinol/.local/share/fonts
xset +fp /home/zerinol/.fonts
xset fp rehash
xset -b &

# (ps x | grep bspswallow | grep -v grep) || bspswallow &

[ -x $HOME/.local/bin/dual_monitor ] && dual_monitor  2>&1 >> "$LOGINLOG"

# Set pulseaudio profile saida analogica
pacmd set-card-profile alsa_card.pci-0000_00_1f.3 output:analog-stereo

bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor HDMI-1 -d 6 7 8 9 0
bspc wm -O eDP1 HDMI-1

bspc config border_width        2
bspc config window_gap          4

bspc config normal_border_color $background
bspc config focused_border_color $color5
bspc config active_border_color $color8
bspc config marked_border_color $color4
bspc config presel_feedback_color $color4

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a XCalc state=floating 
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Gedit state=floating
bspc rule -a mpv state=floating rectangle=640x360+50+70
bspc rule -a *:ncmpcpp state=floating rectangle=1300x412+25+183
bspc rule -a *:pad state=floating rectangle=716x356+400+30
bspc rule -a Emacs state=floating rectangle=775x680+350+30
bspc rule -a zoom state=floating 
bspc rule -a Ramme state=floating
bspc rule -a Zathura state=tiled
bspc rule -a *:Kunst state=floating

$HOME/.config/polybar/launch.sh 2>&1 >> "$LOGINLOG" &
~/.fehbg
